log:
  level: debug
  console:
    encoding: json

session:
  cookie_name: webauthn
  secure: yes
  domain: example.com

listen_address: "0.0.0.0:8080"
external_url: https://auth.example.com

display_name: Webauthn
conveyance_preference: indirect
authenticator_attachment: cross-platform
user_verification_requirement: preferred